version: '3.9'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB:-warrantdb}
      - WEB_ORIGIN=${WEB_ORIGIN}
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase
    secrets:
      - firebase
    ports:
      - "8080:8080"
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5173:80"
secrets:
  firebase:
    file: ./.secrets/asap-bail-books-firebase-adminsdk-fbsvc-71506047b4.json
